version: '3.9'

services:
  db:
    image: 'postgres:15.0-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: DirectoriesDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jml-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: luiselianmg/practica-3-nube-jml
    container_name: DirectoriesServer
    restart: on-failure
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - jml-network

volumes:
  postgres_data:
    driver: local
    dirver_opts:
      type: "nfs"
      o: "add=nfssrvr01,rw"
      device: "/var/lib/postgresql/data"

networks:
  jml-network:
    driver: overlay