version: '3'

services:
  app:
    image: webserver_jml
    container_name: WebServer
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: WebServerDB
    volumes:
      - ./postgres:/var/lib/postgresql/data