version: '3.9'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: DirectoriesDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jml-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: luiselianmg/practica-3-nube-jml
    container_name: DirectoriesServer
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - jml-network

volumes:
  postgres_data:

networks:
  jml-network:
    driver: bridge